setting: cruise_IDM #RL_IDM
configuration:
  batch_SZ_2:
    goal: 2
    x_g: [120, 120]
    y_g: [-2, 2]
    file: "stats/New/BatchSize/No-Time-Budget/mpc_car_batch_data_2_goals.txt"
    weights: [50, 50, 0, 0]

  batch_SZ_4:
    goal: 4
    x_g: [120, 120, 120, 120]
    y_g: [-4, -2, 2, 4]
    file: "stats/New/BatchSize/No-Time-Budget/mpc_car_batch_data_4_goals.txt"
    weights: [50, 50, 0, 0]

  batch_SZ_6:
    goal: 6
    x_g: [120, 120, 120, 120, 120, 120]
    y_g: [-6, -4, -2, 2, 4, 6]
    file: "stats/New/BatchSize/No-Time-Budget/mpc_car_batch_data_6_goals.txt"
    weights: [50, 50, 0, 0]

  batch_SZ_8:
    goal: 8
    x_g: [120, 120, 120, 120, 120, 120, 120, 120]
    y_g: [-8, -6, -4, -2, 2, 4, 6, 8]
    file: "stats/New/BatchSize/No-Time-Budget/mpc_car_batch_data_8_goals.txt"
    weights: [50, 50, 0, 0]

  batch_SZ_10:
    goal: 10
    x_g: [120, 120, 120, 120, 120, 120, 120, 120, 120, 120]
    y_g: [-10, -8, -6, -4, -2, 2, 4, 6, 8, 10]
    file: "stats/New/BatchSize/No-Time-Budget/mpc_car_batch_data_10_goals.txt"
    weights: [50, 50, 0, 0]

  batch_SZ_12:
    goal: 12
    x_g: [120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 130, 130]
    y_g: [-10, -8, -6, -4, -2, 0, 2, 4, 6, 8, 10, 0]
    file: "stats/New/BatchSize/No-Time-Budget/mpc_car_batch_data_12_goals.txt"
    weights: [50, 50, 0, 0]

  batch_SZ_14:
    goal: 14
    x_g: [120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 130, 130, 130]
    y_g: [-10, -8, -6, -4, -2, 0, 2, 4, 6, 8, 10, 0, -2, 2]
    file: "stats/New/BatchSize/No-Time-Budget/mpc_car_batch_data_14_goals.txt"
    weights: [50, 50, 0, 0]
    
  batch_SZ_16:
    goal: 16
    x_g: [120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 130, 130, 130, 130, 130]
    y_g: [-10, -8, -6, -4, -2, 0, 2, 4, 6, 8, 10, 0, -2, 2, 4, -4]
    file: "stats/New/BatchSize/No-Time-Budget/mpc_car_batch_data_16_goals.txt"
    weights: [50, 50, 0, 0]

  batch_SZ_20:
    goal: 20
    x_g: [120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 130, 130, 130, 130, 130, 130, 130, 130, 130]
    y_g: [-10, -8, -6, -4, -2, 0, 2, 4, 6, 8, 10, 0, -2, 2, 4, -4, 6, -6, -8, 8]
    file: "stats/New/BatchSize/No-Time-Budget/mpc_car_batch_data_20_goals.txt"
    weights: [50, 50, 0, 0]

    
  #cruise_IDM:
    #goal: 11.0
    #x_g: [120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120]
    #y_g: [-10, -8, -6, -4, -2, 0, 2, 4, 6, 8, 10]
    #file: "stats/New/Cruise/No-Time-Budget/mpc_car_batch_data_11_goals.txt"
    #weights: [50, 50, 0, 0]
  
  #cruise_IDM:
    #goal: 7.0
    #x_g: [120, 120, 120, 120, 120, 120, 120]
    #y_g: [-5.25, -3.5, -1.75, 0, 1.75, 3.5, 5.25]
    #file: "stats/New/Cruise/No-Time-Budget/mpc_car_batch_data_11_goals.txt"
    #weights: [0, 50, 50, 0]

  cruise_IDM:
    goal: 12.0
    x_g: [60, 60, 60, 70, 70, 70, 80, 80, 80, 90, 90, 90]
    #x_g: [65, 65, 65, 75, 75, 75, 85, 85, 85, 95, 95, 95]
    y_g: [-1.75, 0, 1.75, -1.75, 0, 1.75, -1.75, 0, 1.75, -1.75, 0, 1.75]
    file: "data/RAL/2_lane_12_goals.txt"
    weights: [0, 5, 100, 0]

  #cruise_IDM:
  #  goal: 12.0
  #  x_g: [60, 60, 60, 70, 70, 70, 80, 80, 80, 90, 90, 90]
  #  #x_g: [65, 65, 65, 75, 75, 75, 85, 85, 85, 95, 95, 95]
  #  y_g: [1.75, 3.5, 5.25, 1.75, 3.5, 5.25, 1.75, 3.5, 5.25, 1.75, 3.5, 5.25]
  #  file: "stats/New/Cruise/No-Time-Budget/mpc_car_batch_data_11_goals.txt"
  #  weights: [0, 50, 50, 0]

  #cruise_IDM:
  #  goal: 3.0
  #  x_g: [30, 30, 30]
  #  #x_g: [65, 65, 65, 75, 75, 75, 85, 85, 85, 95, 95, 95]
  #  y_g: [-1.75, 0, 1.75]
  #  file: "stats/New/Cruise/No-Time-Budget/mpc_car_batch_data_11_goals.txt"
  #  weights: [0, 50, 50, 0]


  HSRL_IDM:
    goal: 11
    x_g: [150, 155, 160, 165, 170, 175, 160, 160, 160, 160, 160]
    y_g: [-10, -10, -10, -10, -10, -10, -6, -2, 2 ,6, 10] 
    file: "stats/New/HighSpeed_RightLane/No-Time-Budget/mpc_car_batch_data_11_goals.txt"
    weights: [0, 50, 25, 25]

  RL_IDM:
    goal: 11
    x_g: [110, 115, 120, 125, 130, 135, 120, 120, 120, 120, 120]
    y_g: [-10, -10, -10, -10, -10, -10, -6, -2, 2 ,6, 10] 
    file: "stats/New/RightLane/No-Time-Budget/mpc_car_batch_data_11_goals.txt"
    weights: [0, 50, 50, 0]

  cruise_NGSIM:
    goal: 11
    x_g: [120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120]
    y_g: [-10, -8, -6, -4, -2, 0, 2, 4, 6, 8, 10]
    file: "stats/New/NGSIM/No-Time-Budget/cruise/mpc_car_batch_data_11_goals_0_ngsim.txt"
    weights: [50, 50, 0, 0]


  HSRL_NGSIM:
    goal: 11
    x_g: [150, 155, 160, 165, 170, 175, 160, 160, 160, 160, 160]
    y_g: [-10, -10, -10, -10, -10, -10, -6, -2, 2 ,6, 10] 
    file: "stats/New/NGSIM/No-Time-Budget/hsrl/mpc_car_batch_data_11_goals_0_ngsim.txt"
    weights: [0, 50, 25, 25]



